### ISSUE TITLE
Feature Request - Specify the database schema

### ISSUE THREAD

**Issue by ccmjga** [Enaium/jimmer-gradle#2]
Database: Postgresql

Some specific schemas are not part of the business and do not want to create entity interfaces.

```yml
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: public
```

![Image](https://github.com/user-attachments/assets/b5aab1bd-332f-45c2-b360-871242297172)

Want to be able to specify the schema in a couple of ways.
![Image](https://github.com/user-attachments/assets/de11129a-3942-4e5b-881c-93ba3876506a)
